openapi: 3.0.3
info:
  title: Accord Project Agreement Protocol (APAP)
  version: 1.0.0
  description: API for managing agreement templates and generating documents

paths:
  /templates:
    get:
      summary: Get available templates
      responses:
        "200":
          description: A list of templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Template"

  /generate:
    post:
      summary: Generate a document from a template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateRequest"
      responses:
        "200":
          description: Generated document response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateResponse"
        "400":
          description: Invalid request

components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string

    GenerateRequest:
      type: object
      required:
        - templateId
        - data
      properties:
        templateId:
          type: string
        data:
          type: object

    GenerateResponse:
      type: object
      properties:
        status:
          type: string
        generatedDocument:
          type: string
